name: CI Maven

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      - name: Setup deepinthink/amoeba
        uses: deepinthink/amoeba/.github/actions/setup-amoeba/java@main

      - name: Build && Install blink-specification-im
        run: cd specification/im/java/blink-specification-im && ./mvnw install -B

      - name: Build && Install blink-specification-component
        run: cd specification/component/java/blink-specification-component && ./mvnw install -B

      - name: Build && Install blink-spring-im
        run: cd infrastructure/framework/java/blink-spring-im && ./mvnw install -B

      - name: Build && Install blink-spring-im-gateway
        run: cd components/gateway/java/blink-spring-im-gateway && ./mvnw install -B

      - name: Build && Install blink-benchmark
        run: cd templates/benchmark/java/blink-benchmark && ./mvnw install

      - name: Build && Install blink-chat
        run: cd templates/chat/java/blink-spring-im-chat && ./mvnw install

      - name: Build && Install blink-talk
        run: cd templates/talk/java/blink-spring-im-talk && ./mvnw install
